flaskapp/main/routes.py
from flask import render_template, request, Blueprint, url_for
from flaskapp import login_manager
from flaskapp.models import Post
from flask_login import current_user, login_required
from flaskapp.main.forms import SearchForm
from flaskapp.main.utils import the_device

main = Blueprint('main', __name__)

@main.route("/home",methods=["GET","POST"])
@main.route("/",methods=["GET","POST"])
@login_required
def home():
        image_file = url_for('static', filename=f"images/{current_user.image_file}")
        form = SearchForm()
        posts = Post.query.filter_by(user_id=current_user.id).order_by(Post.date_posted.desc()).all()
        if request.method == "GET":
                if the_device():
                        return render_template("index-mobile.html",title="HOME-MOBILE", image_file=image_file, posts=posts, form=form, device=the_device())
                else:
                        return render_template("index.html",title="HOME", image_file=image_file, posts=posts, form=form, device=the_device())
        elif request.method == "POST":
                search_results = []
                for item in posts:
                        if item.title.lower().__contains__(form.searchterm.data.lower()) or item.content.lower().__contains__(form.searchterm.data.lower()):
                                search_results.append(item)
                if the_device():
                        return render_template("index-mobile.html",title="HOME-MOBILE", image_file=image_file, posts=search_results, form=form, device=the_device())
                else:
                        return render_template("index.html",title="HOME", image_file=image_file, posts=search_results, form=form, device=the_device())

@main.route("/about")
def about():
        return '<h1 style="font-family:\'Poppins\'"> The about Page ! 😁 </h1>'

flaskapp/posts/routes.py
from flaskapp.models import Post
from flask import render_template, url_for, flash,redirect, request, Blueprint
from flaskapp import db
from flaskapp.posts.forms import NoteForm
from flask_login import current_user, login_required
from flaskapp.main.utils import the_device
from datetime import datetime

posts = Blueprint('posts', __name__)

@posts.route("/note/new", methods=["GET", "POST"])
@login_required
def new_note():
        form = NoteForm()
        if form.validate_on_submit():
                post = Post(title=form.title.data, content=form.content.data, author=current_user)
                db.session.add(post)
                db.session.commit()
                flash("Your note has been added!", "success")
                return redirect(url_for("main.home"))
        if the_device():
                return render_template("addnotes-mobile.html", title="NEWNOTE-MOBILE", form=form, device=the_device())
        else:
                return render_template("addnotes.html", title="NEWNOTE", form=form,device=the_device())

@posts.route("/post/<int:post_id>")
def post(post_id):
        post = Post.query.get_or_404(post_id)
        if the_device():
                return render_template("viewnote-mobile.html", title="View Note-Mobile", post=post, device=the_device())
        else:
                return render_template("viewnote.html", title="View Note", post=post, device=the_device())

@posts.route("/post/<int:post_id>/u",methods=["GET", "POST"])
@login_required
def update_post(post_id):
        post = Post.query.get_or_404(post_id)
        form = NoteForm()
        if form.validate_on_submit():
                post.title = form.title.data
                post.content = form.content.data
                post.date_posted = datetime.utcnow()
                db.session.commit()
                flash("Your post has been updated!", "success")
                return redirect(url_for("posts.post", post_id=post.id))
        elif request.method == "GET":
                form.title.data = post.title
                form.content.data = post.content
        if the_device():
                return render_template("addnotes-mobile.html", title="Update Post-Mobile", form=form, device=the_device())
        else:
                return render_template("addnotes.html", title="Update Post", form=form, device=the_device())

@posts.route("/post/<int:post_id>/d",methods=["POST"])
@login_required
def delete_post(post_id):
        post = Post.query.get_or_404(post_id)
        db.session.delete(post)
        db.session.commit()
        flash("Your post has been deleted!", "success")
        return redirect(url_for("main.home"))

flaskapp/users/routes.py
from flaskapp.models import User
from flask import render_template, url_for, flash,redirect, request, Blueprint
from flaskapp import db, bcrypt
from flaskapp.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flask_login import login_user, logout_user, current_user, login_required
from flaskapp.users.utils import save_picture, send_reset_email
from flaskapp.main.utils import the_device

users = Blueprint('users', __name__)

@users.route("/register",methods=["GET","POST"])
def registration():
        if current_user.is_authenticated:
                return redirect(url_for("main.home"))
        form = RegistrationForm()
        if form.validate_on_submit():
                hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
                user = User(username=form.username.data, email=form.email.data.strip(), password=hashed_password)
                db.session.add(user)
                db.session.commit()
                flash(f"Successfully created account for {form.username.data}!", "success")
                return redirect(url_for("users.login"))
        if the_device():
                return render_template("register-mobile.html", title="REGISTER-MOBILE", form=form,device=the_device())
        else:
                return render_template("register.html", title="REGISTER", form=form, device=the_device())

@users.route("/login", methods=["GET","POST"])
def login():
        if current_user.is_authenticated:
                return redirect(url_for("main.home"))
        form = LoginForm()
        if form.validate_on_submit():
                user = User.query.filter_by(email=form.email.data.strip()).first()
                if user and bcrypt.check_password_hash(user.password, form.password.data):
                        login_user(user, remember=form.remember.data)
                        next_page = request.args.get('next')
                        return redirect(next_page) if next_page else redirect(url_for("main.home"))
                else:
                        flash("Login unsuccessful. please check the details.", "error")
        if the_device():
                return render_template("login-mobile.html", title="LOGIN-MOBILE", form=form, device=the_device())
        else:
                return render_template("login.html", title="LOGIN", form=form,device=the_device())

@users.route("/logout")
def logout():
        logout_user()
        return redirect(url_for("users.login"))

@users.route("/account", methods=["GET","POST"])
@login_required
def account():
        form = UpdateAccountForm()
        if form.validate_on_submit():
                if form.picture.data:
                        picture_file = save_picture(form.picture.data)
                        current_user.image_file = picture_file
                current_user.username = form.username.data
                current_user.email = form.email.data
                db.session.commit()
                flash("Your account has been updated.","info")
                return redirect(url_for("users.account"))
        elif request.method == "GET":
                form.username.data = current_user.username
                form.email.data = current_user.email
        image_file = url_for('static', filename=f"images/{current_user.image_file}")
        if the_device():
                return render_template("account-mobile.html", title="ACCOUNT-MOBILE", image_file=image_file, form=form,device=the_device())
        else:
                return render_template("account.html", title="ACCOUNT", image_file=image_file, form=form, device=the_device())

@users.route("/reset_password", methods=["GET", "POST"])
def reset_password():
        if current_user.is_authenticated:
                return redirect(url_for("main.home"))
        form = RequestResetForm()
        if form.validate_on_submit():
                user = User.query.filter_by(email=form.email.data).first()
                if user:
                        send_reset_email(user)
                        flash("An email has been sent with instructions to reset your password.","info")
                        return redirect(url_for("users.login"))
        if the_device():
                return render_template("request_reset-mobile.html", title="Reset Password-Mobile", form=form, device=the_device())
        else:
                return render_template("request_reset.html", title="Reset Password", form=form, device=the_device())

@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
        if current_user.is_authenticated:
                return redirect(url_for("main.home"))
        user = User.verify_reset_token(token)
        if user is None:
                flash("That is an invalid token","warning")
                return redirect(url_for("users.reset_password"))
        form = ResetPasswordForm()
        if form.validate_on_submit():
                hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
                user.password = hashed_password
                db.session.commit()
                flash(f"Successfully changed password for {user.username}!", "success")
                return redirect(url_for("users.login"))
        if the_device():
                return render_template("reset-mobile.html",title="Reset Password-Mobile", form=form, device=the_device())
        else:
                return render_template("reset.html",title="Reset Password", form=form, device=the_device())

flaskapp/templates/about.html
{% extends "layout.html" %}
{% block content %}
	<h1>ABOUT PAGE</h1>
{% endblock content %}

flaskapp/templates/account-mobile.html
{% extends "layout.html" %}
{% block content %}
        <div class="container">
                <img class="image" src="{{  image_file }}">
                <div class="gp">
                        <span class="tag">Account Info</span>
                        <form  class="the_form" method="POST" enctype="multipart/form-data">
                                {{ form.hidden_tag() }}
                                <div class="form_div">
                                        <span class="field">
                                                {{ form.username.label(class="form-control-label") }}
                                                {% if form.username.errors %}
                                                        {{ form.username(class="form-control ") }}
                                                        <div>
                                                                {% for error in form.username.errors %}
                                                                        <span class="error">{{ error }}</span>
                                                                {% endfor %}
                                                        </div>
                                                {% else %}
                                                        {{ form.username(class="form-control ") }}
                                                {% endif %}
                                        </span>
                                        <span class="field">
                                                {{ form.email.label(class="form-control-label") }}
                                                {% if form.email.errors %}
                                                        {{ form.email(class="form-control ") }}
                                                        <div>
                                                                {% for error in form.email.errors %}
                                                                        <span class="error">{{ error }}</span>
                                                                {% endfor %}
                                                        </div>
                                                {% else %}
                                                        {{ form.email(class="form-control ") }}
                                                {% endif %}
                                        </span>
                                        <span class="field button-wrap">
                                                {{ form.picture.label(class="button form-control-label") }}
                                                {{ form.picture(class="form-control-pic") }}
                                                {% if form.picture.errors %}
                                                        {{ form.picture(class="form-control ") }}
                                                        <div>
                                                                {% for error in form.picture.errors %}
                                                                        <span class="error">{{ error }}</span>
                                                                {% endfor %}
                                                        </div>
                                                {% endif  %}
                                        </span>
                                </div>
                                <span class="submit-button">
                                        {{ form.submit(class="btn") }}
                                </span>
                        </form>
                </div>
        </div>

{% endblock content %}

flaskapp/templates/account.html
{% extends "layout.html" %}
{% block content %}
        <div class="container">
                <img class="image" src="{{  image_file }}">
                <div class="gp">
                        <span class="tag">Account Info</span>
                        <form  class="the_form" method="POST" enctype="multipart/form-data">
                                {{ form.hidden_tag() }}
                                <div class="form_div">
                                        <span class="field">
                                                {{ form.username.label(class="form-control-label") }}
                                                {% if form.username.errors %}
                                                        {{ form.username(class="form-control ") }}
                                                        <div>
                                                                {% for error in form.username.errors %}
                                                                        <span class="error" >{{ error }}</span>
                                                                {% endfor %}
                                                        </div>       
                                                {% else %}
                                                        {{ form.username(class="form-control ") }}
                                                {% endif %}
                                        </span>
                                        <span class="field">
                                                {{ form.email.label(class="form-control-label") }}
                                                {% if form.email.errors %}
                                                        {{ form.email(class="form-control ") }}
                                                        <div>
                                                                {% for error in form.email.errors %}
                                                                        <span class="error" >{{ error }}</span>
                                                                {% endfor %}
                                                        </div>       
                                                {% else %}
                                                        {{ form.email(class="form-control ") }}
                                                {% endif %}
                                        </span>
                                        <span class="field button-wrap">
                                                {{ form.picture.label(class="button form-control-label") }}
                                                {{ form.picture(class="form-control-pic") }}
                                                {% if form.picture.errors %}
                                                        {{ form.picture(class="form-control ") }}
                                                        <div>
                                                                {% for error in form.picture.errors %}
                                                                        <span class="error" >{{ error }}</span>
                                                                {% endfor %}
                                                        </div>      
                                                {% endif  %}
                                        </span>
                                </div>
                                <span class="submit-button">
                                        {{ form.submit(class="btn") }}
                                </span>
                        </form>
                </div>
        </div>
        
{% endblock content %}

flaskapp/templates/addnotes-mobile.html
{% extends "layout.html" %}
{% block content %}
        <form  class="the_form" method="POST">
                {{ form.hidden_tag() }}
                <div class="form_div">
                        <span class="field">
                                {{ form.title.label(class="form-control-label") }}
                                {% if form.title.errors %}
                                        {{ form.title(class="form-control ") }}
                                        <div>
                                                {% for error in form.title.errors %}
                                                        <span class="error">{{ error }}</span>
                                                {% endfor %}
                                        </div>       
                                {% else %}
                                        {{ form.title(class="form-control ") }}
                                {% endif %}
                        </span>
                        <span class="field">
                                {{ form.content.label(class="form-control-label") }}
                                {% if form.content.errors %}
                                        {{ form.content(class="form-control ") }}
                                        <div>
                                                {% for error in form.content.errors %}
                                                        <span class="error">{{ error }}</span>
                                                {% endfor %}
                                        </div>       
                                {% else %}
                                        {{ form.content(class="form-control-c form-control") }}
                                {% endif %}
                        </span>
                </div>
                <span class="submit-button">
                        {{ form.submit(class="btn") }}
                </span>
        </form>
{% endblock %}

flaskapp/templates/index.html
{% extends "layout.html" %}
{% block content %}
        <div class="header">
                <div class="dp"><img  class="dp-image" src="{{ image_file }}"></div>
                <form class="search-wrapper" method="POST">
                        {{ form.hidden_tag() }} 
                        {{ form.searchterm(class="search-bar", placeholder="Looking for something....")}}
                        {{ form.submit(class="btn") }}
                </form>
                <div class="settings" id="js-click">
                        <span></span>
                        <span></span>
                        <span></span>
                </div>
                <div class="menu" id="js-menu">
                        <a href="{{ url_for('users.account') }}"><span>Account</span></a>
                        <a href="{{ url_for('main.about') }}"><span>About</span></a>
                        {% if current_user.is_authenticated %}
                                <a href="{{ url_for('users.logout') }}"><span>Log out</span></a>
                        {% endif %}
                </div>
        </div>
        <div class="greetings">
                <span>
                        Hey there {{ current_user.username }}!
                </span>
        </div>
        <div class="user-notes">
                {% for post in posts %}
                <a class="card" href="{{ url_for('posts.post', post_id=post.id) }}">
                        <div>
                                <div class="card-title-js">{{ post.title }}</div>
                                <div class="card-body card-body-js">{{ post.content }}</div>
                                <div class="card-date">{{ post.date_posted.strftime('%Y-%m-%d') }}</div>
                        </div>
                </a>
                {% endfor %}
        </div>
        <a href="{{ url_for('posts.new_note') }}">
                <div class="add-note">
                                <button class="btn-1" type="button">+</button>
                </div>
        </a>
{% endblock %}

flaskapp/templates/login-mobile.html
{% extends "layout.html" %}
{% block content %}
        <div class="content-section">
                <form  class="the_form" method="POST">
                        {{ form.hidden_tag() }}
                        <span class="join">SIGN IN!</span>
                        <div class="form_div">
                                <span class="field">
                                        {{ form.email.label(class="form-control-label") }}
                                        {% if form.email.errors %}
                                                {{ form.email(class="form-control ") }}
                                                <div>
                                                        {% for error in form.email.errors %}
                                                                <span class="error">{{ error }}</span>
                                                        {% endfor %}
                                                </div>       
                                        {% else %}
                                                {{ form.email(class="form-control ") }}
                                        {% endif %}
                                </span>
                                <span class="field">
                                        {{ form.password.label(class="form-control-label") }}
                                        {% if form.password.errors %}
                                                {{ form.password(class="form-control ") }}
                                                <div>
                                                        {% for error in form.password.errors %}
                                                                <span class="error">{{ error }}</span>
                                                        {% endfor %}
                                                </div>       
                                        {% else %}
                                                {{ form.password(class="form-control ") }}
                                        {% endif %}
                                </span>
                        </div>
                        <div class="form-check">
                                {{ form.remember(class="form-check-input") }}
                                {{ form.remember.label(class="form-check-label") }}
                        </div>
                        <span class="submit-button">
                                {{ form.submit(class="btn") }}
                                <small class="Forgot Password">
                                        <a href="{{ url_for('users.reset_password') }}">Forgot Password?</a>
                                </small>
                        </span>
                </form>
                <div class="login-button">
                <small class="login-qn">
                        Don't have an account? <a class="login-redirect" href="{{ url_for('users.registration') }}">Sign Up</a>
                </small>
                </div>
        </div>
{% endblock %}
        

flaskapp/templates/login.html
{% extends "layout.html" %}
{% block content %}
        <div class="content-section">
                <form  class="the_form" method="POST">
                        {{ form.hidden_tag() }}
                        <span class="join">SIGN IN!</span>
                        <div class="form_div">
                                <span class="field">
                                        {{ form.email.label(class="form-control-label") }}
                                        {% if form.email.errors %}
                                                {{ form.email(class="form-control ") }}
                                                <div>
                                                        {% for error in form.email.errors %}
                                                                <span class="error">{{ error }}</span>
                                                        {% endfor %}
                                                </div>       
                                        {% else %}
                                                {{ form.email(class="form-control ") }}
                                        {% endif %}
                                </span>
                                <span class="field">
                                        {{ form.password.label(class="form-control-label") }}
                                        {% if form.password.errors %}
                                                {{ form.password(class="form-control ") }}
                                                <div>
                                                        {% for error in form.password.errors %}
                                                                <span class="error">{{ error }}</span>
                                                        {% endfor %}
                                                </div>       
                                        {% else %}
                                                {{ form.password(class="form-control ") }}
                                        {% endif %}
                                </span>
                        </div>
                        <div class="form-check">
                                {{ form.remember(class="form-check-input") }}
                                {{ form.remember.label(class="form-check-label") }}
                        </div>
                        <span class="submit-button">
                                {{ form.submit(class="btn") }}
                                <small class="Forgot Password">
                                        <a href="{{ url_for('users.reset_password') }}">Forgot Password?</a>
                                </small>
                        </span>
                </form>
                <div class="login-button">
                <small class="login-qn">
                        Don't have an account? <a class="login-redirect" href="{{ url_for('users.registration') }}">Sign Up</a>
                </small>
        </div>
        </div>
{% endblock %}
        

flaskapp/templates/request_reset-mobile.html
{% extends "layout.html" %}
{% block content %}
        <div class="content-section">
                <form  class="the_form" method="POST">
                        {{ form.hidden_tag() }}
                        <span class="join">Reset Password</span>
                        <div class="form_div">
                                <span class="field">
                                        {{ form.email.label(class="form-control-label") }}
                                        {% if form.email.errors %}
                                                {{ form.email(class="form-control ") }}
                                                <div>
                                                        {% for error in form.email.errors %}
                                                                <span class="error">{{ error }}</span>
                                                        {% endfor %}
                                                </div>       
                                        {% else %}
                                                {{ form.email(class="form-control ") }}
                                        {% endif %}
                                </span>
                                
                        </div>
                        <div class="buttons">
                                <span class="submit-button">
                                        {{ form.submit(class="btn") }}
                                </span>
                                <a class="reset" href="{{ url_for('users.registration') }}"><button class="btn" type="button">Register</button></a>
                        </div>
                        
                </form>
        </div>
{% endblock %}
        

flaskapp/templates/viewnote-mobile.html
{% extends "layout.html" %}
{% block content %}
	<div class="note_context">
                <span class="field">
                        <label for="title">Title</label>
        		<input class="title" value="{{ post.title }}" readonly>
                </span>
                <span class="field">
                        <label for="note">Content</label>
                        <textarea class="note" name="content" id="content" readonly>{{ post.content }}</textarea>
                </span>
        </div>
        <div class="buttons">
                <a href="{{ url_for('posts.update_post', post_id=post.id )}}"><button class="btn">Update Note</button></a>
                <form action="{{ url_for('posts.delete_post', post_id=post.id ) }}" method="POST">
                        <input type="submit" class="delete-button" value="Delete">
                </form>
        </div>
        <span class="date-time-stamp dts">Edited on {{ post.date_posted.strftime('%Y-%m-%d') }}</span>
{% endblock %}

flaskapp/templates/viewnote.html
{% extends "layout.html" %}
{% block content %}
	<div class="note_context">
                <label for="title">Title</label>
		<input class="title" value="{{ post.title }}" readonly>
		<label for="note">Content</label>
                <textarea class="note" name="content" id="content" readonly>{{ post.content }}</textarea>
        </div>
        <div class="buttons">
                <a href="{{ url_for('posts.update_post', post_id=post.id )}}"><button class="btn" >Update Note</button></a>
                <form action="{{ url_for('posts.delete_post', post_id=post.id ) }}" method="POST">
                        <input type="submit" class="delete-button" value="Delete">
                </form>
        </div>
        <span class="date-time-stamp dts">Edited on {{ post.date_posted.strftime('%Y-%m-%d') }}</span>
{% endblock %}